source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!

target 'MapScenarios' do
  use_frameworks!

  pod 'PWMapKit', :git => 'https://github.com/phunware/maas-mapping-ios-sdk.git', :tag => '3.15.1'
  
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
end
