source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!

target 'MapScenarios' do
  use_frameworks!

  pod 'PWMapKit', :git => 'https://github.com/phunware/maas-mapping-ios-sdk.git', :tag => 'v3.13.0-beta-06'

  # Explicitly point to all Phunware beta SDKs that PWMapKit depends on
  pod 'PWCore', :git => 'https://github.com/phunware/maas-core-ios-sdk.git', :tag => 'v3.12.0-beta-04'
  pod 'PWLocation', :git => 'https://github.com/phunware/maas-location-ios-sdk.git', :tag => 'v3.12.0-beta-03'
  pod 'PWLocation/MistProvider', :git => 'https://github.com/phunware/maas-location-ios-sdk.git', :tag => 'v3.12.0-beta-03'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
end
