source 'git@github.com:phunware/phunware-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘7.0’
xcodeproj 'LoadMap.xcodeproj'
inhibit_all_warnings!


target :LoadMap do
    pod 'PW_MapKit’, ‘3.0.0’
end
