source 'ssh://git@github.com/CocoaPods/Specs.git'
source 'ssh://git@bitbucket.phunware.com:7999/misc/cocoapods-sdk-ios.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'LocationSharing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationSharing
  pod 'PWMapKit'
end
