source 'ssh://git@github.com/CocoaPods/Specs.git'
source 'ssh://git@bitbucket.phunware.com:7999/misc/cocoapods-sdk-ios.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'LocationSharing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationSharing
  pod 'PWMapKit', :path => '/Users/patrickdunshee/repos/forks/mapping-sdk-ios'
  #pod 'PWLocation', :path => '/Users/patrickdunshee/repos/forks/location-sdk-ios'
  pod 'StepInsideSdk', :http => 'https://phunware-765bf3b3:6dfeef13a4494f79@artifacts.senionlab.com/pods/stepinside-sdk/5.1.1.zip'
  pod 'SVPulsingAnnotationView', :git => 'https://github.com/TransitApp/SVPulsingAnnotationView'
end
