source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!

target 'PhunMaps' do
use_frameworks!

  pod 'PWLocation/MistProvider'
  pod 'PWMapKit', '3.11.0'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
end
