source 'ssh://git@github.com/CocoaPods/Specs.git'
source 'ssh://git@bitbucket.phunware.com:7999/misc/cocoapods-sdk-ios.git'
inhibit_all_warnings!

target 'Maps-Samples' do
    pod 'PWMapKit', '3.1.4'
    pod 'JDStatusBarNotification'
    pod 'MBProgressHUD'
    pod 'PureLayout'
    pod 'ZFTokenField'
    pod 'Fabric'
    pod 'Crashlytics'
end
